# Generated by Django 4.1 on 2022-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Adults', models.IntegerField(default=1)),
                ('Children', models.IntegerField(default=0)),
                ('Room', models.IntegerField(default=0)),
                ('Breakfast', models.BooleanField(default=False)),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
            ],
        ),
    ]
